# The URL the site will be built for
base_url = "https://primamateria.github.io/blog"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "Prima​Materia's"
theme = "anpu-zola-theme"

taxonomies = [
    { name = "categories" },
    { name = "tags" },
]

# Syntax highlighting configuration (optional)
[markdown.highlighting]
# When set to "true", missing highlight languages are treated as errors. Defaults to false but recommended to set to true.
error_on_missing_language = false

# Whether to use inline hex colours (`inline`) or CSS classes (`class`) 
style = "inline"

# Selecting a theme is always required: you have a choice between single (1) or dual themes (2).
# Only outputting CSS classes like before 0.22 is not possible anymore.
# 1. If you use a single theme, put its name here. See the syntax highlighting page for the possible choices.
theme = "one-light"

# 2. If you want light/dark themes, use the 2 fields below instead. See the syntax highlighting page for the possible choices.
light_theme = ""
dark_theme = ""

# A list of files for additional JSON TextMate grammars
extra_grammars = []

# A list of files for additional JSON TextMate themes
# Get themes from https://textmate-grammars-themes.netlify.app/
extra_themes = []

[extra]
# Put all your custom variables here
author = "Matus Benko"
github = "PrimaMateria"
anpu_date_format="%A %d %B %Y"
