# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build_and_deploy
        uses: PrimaMateria/zola-deploy-action@master
        env: 
          BUILD_DIR: primamateria-blog
          PAGES_BRANCH: gh-pages          
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
